### ISSUE TITLE
ModuleNotFoundError: No module named 'pwd'

### ISSUE THREAD

**Issue by ramz35** [dakshesh14/anukool#2]
Traceback (most recent call last):
  File "C:\Repository\Coding\GenerativeAI\anukool\main.py", line 14, in <module>
    from ingest import get_vector_database
  File "C:\Repository\Coding\GenerativeAI\anukool\ingest.py", line 10, in <module>
    from langchain_community.document_loaders import (
  File "C:\Repository\Coding\GenerativeAI\anukool\venv\lib\site-packages\langchain_community\document_loaders\__init__.py", line 163, in <module>
    from langchain_community.document_loaders.pebblo import PebbloSafeLoader
  File "C:\Repository\Coding\GenerativeAI\anukool\venv\lib\site-packages\langchain_community\document_loaders\pebblo.py", line 5, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

running this on a Windows machine and it's a current known issue https://github.com/langchain-ai/langchain/discussions/17513

edit:
had to use the following to proceed
pip install langchain-community==0.0.19
pip install langchain==0.1.6

**Comment by dakshesh14** [comment]
Marking this issue as closed since both the packages are on `requirements.txt`.
